server:
  servlet:
    context-path: ${context:/codenjoy-client-runner}

service:
  solutionFolderPath: "./solutions"
  solutionFolderPattern: "dd-MM-yyyy'T'HH_mm_ss"
  codenjoyUrlRegex: "^https?://[0-9A-Za-z_.\\-]+/codenjoy-contest/board/player/([\\w]+)\\?code=([\\w]+)"