server:
  servlet:
    context-path: ${context:/codenjoy-client-runner}

service:
  solutionFolder:
    path: "./solutions"
    pattern: "yyyy-MM-dd'_'HH-mm-ss"
  serverRegex: "^https?://[0-9A-Za-z_.\\-]+/codenjoy-contest/board/player/([\\w]+)\\?code=([\\w]+)"

docker:
  container:
    memoryLimitMB: 0
    cpuPeriod: 100000
    cpuQuota: -1