version: "3.9"
services:
  server:
    env_file:
      - client-runner.env
    build: ..
    ports:
      - "${PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SOLUTIONS_FOLDER}:/solutions